import type { Metadata } from 'next'
import { Inter as FontSans } from "next/font/google";
import './globals.css'
import Header from '@/components/layout/header'
import { Footer } from '@/components/layout/footer'
import { ThemeProvider } from '@/components/theme/theme-provider'
import { cn } from '@/lib/utils';

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>
      <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
        <div className="flex flex-col h-full ">
          <div className='z-40'>
            <Header />
          </div>
          <div className="flex-1 w-full m-auto  w-full z-0">{children}</div>

          <div className='w-full'>
          <Footer />
          </div>
        </div>
      </ThemeProvider>
        
      </body>
    </html>
  )
}
