import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/layout/header'
import { Footer } from '@/components/layout/footer'
import { ThemeProvider } from '@/components/theme/theme-provider'
import { cn } from '@/lib/utils';
import Cursor from '@/components/cursor/cursor';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(
          "font-sans antialiased"
        )}>
      <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          
          <Cursor />
        <div className="">
          {/* <div className='z-40'>
            <Header />
          </div> */}
          <div className="">{children}</div>

          {/* <div className='w-full'>
          <Footer />
          </div> */}
        </div>
      </ThemeProvider>
        
      </body>
    </html>
  )
}
